name: migent
description: Tool to run and manage migrations of your database schema
version: 1.1.0
homepage: https://github.com/nyxx-discord/migent

executables:
  glacier:

environment:
  sdk: '^3.5.0'

dependencies:
  logging: ^1.0.1
  postgres: ^3.4.0
  args: ^2.3.0
  path: ^1.8.0

dev_dependencies:
  lints: ^5.0.0
  test: ^1.16.0
