name: migent
description: Tool to run and manage migrations of your database schema
version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  logging: ^1.0.1
  postgres: ^2.3.2

dev_dependencies:
  pedantic: ^1.10.0
  test: ^1.16.0
